# Generated by Django 5.0.3 on 2024-11-21 00:09

import core.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=core.models.recipe_image_file_path),
            preserve_default=False,
        ),
    ]
