# Generated by Django 5.0.3 on 2025-03-01 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updateAt', models.DateTimeField(auto_created=True, auto_now=True)),
                ('createAt', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('reward', models.CharField(max_length=200)),
                ('avilible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updateAt', models.DateTimeField(auto_created=True, auto_now=True)),
                ('createAt', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='EventModel',
        ),
        migrations.AddField(
            model_name='userevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='core_auth.userprofile'),
        ),
        migrations.DeleteModel(
            name='Organizer',
        ),
    ]
